version: '3.9'

services:
  checkcle:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    image: checkcle:local
    container_name: checkcle
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "8091:8091"
    volumes:
      - /opt/pb_data:/mnt/pb_data
    ulimits:
      nofile:
        soft: 4096
        hard: 8192

