import { useState } from "react";
import { useTheme } from "@/contexts/ThemeContext";
import { useLanguage } from "@/contexts/LanguageContext";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ExternalLink, Maximize2, Minimize2, X } from "lucide-react";

interface HTMLReportViewerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  reportUrl: string;
  testName: string;
}

export function HTMLReportViewer({
  open,
  onOpenChange,
  reportUrl,
  testName,
}: HTMLReportViewerProps) {
  const { theme } = useTheme();
  const { t } = useLanguage();
  const [isFullscreen, setIsFullscreen] = useState(false);

  const openInNewTab = () => {
    window.open(reportUrl, "_blank");
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        className={`${
          isFullscreen ? "max-w-[95vw] h-[95vh]" : "max-w-4xl h-[80vh]"
        } flex flex-col ${theme === "dark" ? "bg-gray-900 border-gray-800" : ""}`}
      >
        <DialogHeader className="flex-shrink-0">
          <div className="flex items-center justify-between">
            <DialogTitle className="flex items-center gap-2">
              {t("sitespeedReport") || "Sitespeed.io Report"}: {testName}
            </DialogTitle>
            <div className="flex items-center gap-2">
              <Button
                variant="ghost"
                size="icon"
                onClick={() => setIsFullscreen(!isFullscreen)}
                title={isFullscreen ? t("exitFullscreen") || "Exit Fullscreen" : t("fullscreen") || "Fullscreen"}
              >
                {isFullscreen ? (
                  <Minimize2 className="h-4 w-4" />
                ) : (
                  <Maximize2 className="h-4 w-4" />
                )}
              </Button>
              <Button
                variant="ghost"
                size="icon"
                onClick={openInNewTab}
                title={t("openInNewTab") || "Open in New Tab"}
              >
                <ExternalLink className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </DialogHeader>

        <div className="flex-1 overflow-hidden rounded-lg border">
          {reportUrl ? (
            <iframe
              src={reportUrl}
              className="w-full h-full border-0"
              title={`Sitespeed Report - ${testName}`}
              sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
            />
          ) : (
            <div className="flex items-center justify-center h-full text-muted-foreground">
              {t("noReportAvailable") || "No report available"}
            </div>
          )}
        </div>

        <div className="flex-shrink-0 pt-4 flex justify-between items-center text-sm text-muted-foreground">
          <span>{t("reportGeneratedBy") || "Report generated by"} sitespeed.io</span>
          <Button variant="outline" size="sm" onClick={openInNewTab}>
            <ExternalLink className="h-4 w-4 mr-2" />
            {t("openFullReport") || "Open Full Report"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
